runtime: nodejs20
env: standard

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  NODE_ENV: "production"
  PORT: "8080"

handlers:
  - url: /api/.*
    script: auto
  - url: /.*
    script: auto
